# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

advert_index:
    path:      /
    defaults:
        _controller: AppBundle:Advert:index

advert_showAll:
    path:    /showAll
    defaults:
        _controller: AppBundle:Advert:showAll

adverts_user:
    path: /user/myAdverts
    defaults:
        _controller: AppBundle:Advert:userAdverts

advert_search:
    path:    /search
    defaults:
        _controller: AppBundle:Advert:search

advert_new:
    path:    /user/new
    defaults:
        _controller: AppBundle:Advert:new

advert_show:
    path:    /{id}
    defaults:
        _controller: AppBundle:Advert:show

advert_edit:
    path:    /admin/{id}/edit
    defaults:
        _controller: AppBundle:Advert:edit

advByCat:
    path: /user/advByCat/{catName}
    defaults:
        _controller: AppBundle:Advert:advByCat

advert_categories:
    path: /categories
    defaults:
        _controller: AppBundle:Advert:viewCategorie

advert_menu:
    path:    /menu
    defaults:
        _controller: AppBundle:Advert:indexBase

advert_indexBase:
    path:    /indexBase
    defaults:
        _controller: AppBundle:Advert:menu

advert_delete:
    path: /admin/delete/{id}
    defaults:
        _controller: AppBundle:Advert:delete
        methods:  DELETE

#Administration

admin_index:
    path: /admin/administration
    defaults:
        _controller: AppBundle:Admin:indexAdmin

advert_valid:
    path: /admin/validAdvert
    defaults:
        _controller: AppBundle:Admin:validAdvert