# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mentions_legales:
    path: /mentions-legales
    defaults:
        _controller: AppBundle:App:mentionsLegales

informations:
    path: /informations
    defaults:
        _controller: AppBundle:App:informations

contact:
    path:     /contact
    defaults:
        _controller: AppBundle:App:contact

advert_index:
    path:      /
    defaults:
        _controller: AppBundle:Advert:index

advert_showAll:
    path:    /showAll
    defaults:
        _controller: AppBundle:Advert:showAll

adverts_user:
    path: /user/myAdverts
    defaults:
        _controller: AppBundle:Advert:userAdverts

advert_search:
    path:    /search
    defaults:
        _controller: AppBundle:Advert:search

advert_new:
    path:    /user/new
    defaults:
        _controller: AppBundle:Advert:new

advert_show:
    path:    /{id}
    defaults:
        _controller: AppBundle:Advert:show

advert_edit:
    path:    /user/{id}/edit
    defaults:
        _controller: AppBundle:Advert:edit

advByCat:
    path: /user/advByCat/{catName}
    defaults:
        _controller: AppBundle:Advert:advByCat

advert_menu:
    path:    /menu
    defaults:
        _controller: AppBundle:Advert:indexBase

advert_indexBase:
    path:    /indexBase
    defaults:
        _controller: AppBundle:Advert:menu

advert_delete:
    path: /user/delete/{id}
    defaults:
        _controller: AppBundle:Advert:delete
        methods:  DELETE

#Administration

admin_index:
    path: /admin/administration
    defaults:
        _controller: AppBundle:Admin:indexAdmin

show_advert_unvalid:
    path: /admin/showUnvalidAdvert
    defaults:
        _controller: AppBundle:Admin:showUnvalidAdvert

advert_valid:
    path: /admin/validAdvert
    defaults:
        _controller: AppBundle:Admin:validAdvert

advert_categories:
    path: admin/categories
    defaults:
        _controller: AppBundle:Admin:viewCategories
